//! Manual smoke-test server for the openapi/macro refactor.
//!
//! Run with `cargo run --example demo -p lucyd`, then hit:
//! - http://localhost:3000/docs              (embedded UI)
//! - http://localhost:3000/docs/openapi.json (generated by crates/lucyd-core/src/openapi/)
//! - http://localhost:3000/docs/spec.json
//! - POST http://localhost:3000/api/ping
//! - GET  http://localhost:3000/api/scores?board=main&limit=5
//!
//! The MQTT panel needs a broker speaking WebSocket. One is served from this
//! same process (see [`mqtt_broker`]), so point the panel's Broker field at
//! `ws://localhost:3000/mqtt` — no external broker, no second port.

mod mqtt_broker;

use axum::{
    Router,
    extract::{
        Query,
        ws::{Message, WebSocket, WebSocketUpgrade},
    },
    response::IntoResponse,
    routing::{get, post},
};
use lucyd::{docs_router, lucyd_http, lucyd_mqtt, lucyd_ws};
use mqtt_broker::Publication;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::time::Duration;
use tokio::sync::broadcast::Sender;

#[derive(Deserialize, JsonSchema)]
pub struct Ping {
    pub message: String,
}

#[derive(Serialize, JsonSchema)]
pub struct Pong {
    pub echo: String,
}

#[derive(Deserialize, JsonSchema)]
pub struct ScoreFilters {
    /// Board the scores belong to.
    pub board: String,
    /// Maximum number of rows returned.
    pub limit: Option<u32>,
}

#[derive(Serialize, JsonSchema)]
pub struct Scores {
    pub board: String,
    pub values: Vec<u32>,
}

#[derive(Deserialize, JsonSchema)]
pub struct EventFilters {
    /// Only events from this room are relayed.
    pub room: String,
    /// Maximum number of backlog events replayed on connect.
    pub replay: Option<u32>,
}

#[lucyd_http(
    method = "POST",
    path = "/api/ping",
    tags = "system",
    description = "Echo back the message",
    request = Ping,
    response = Pong,
)]
async fn ping(axum::Json(body): axum::Json<Ping>) -> axum::Json<Pong> {
    axum::Json(Pong { echo: body.message })
}

// `query` documents the query string; `Query<ScoreFilters>` is what actually
// parses it. The macro describes the contract, the extractor enforces it —
// exactly the split between `request = Ping` and `Json<Ping>` above.
#[lucyd_http(
    method = "GET",
    path = "/api/scores",
    tags = "system",
    description = "List scores for a board",
    query = ScoreFilters,
    response = Scores,
)]
async fn scores(Query(filters): Query<ScoreFilters>) -> axum::Json<Scores> {
    let limit = filters.limit.unwrap_or(3) as usize;
    axum::Json(Scores {
        board: filters.board,
        values: (1..=limit as u32).map(|n| n * 100).collect(),
    })
}

// `query` declares the upgrade URL's query string — the only channel a browser
// has at connect time, since the `WebSocket` constructor cannot set headers.
#[lucyd_ws(
    path = "/ws/events",
    tags = "realtime",
    description = "Live event stream",
    query = EventFilters
)]
async fn events(ws: WebSocketUpgrade, Query(filters): Query<EventFilters>) -> impl IntoResponse {
    ws.on_upgrade(move |socket| handle_events(socket, filters))
}

/// Greets the client with what it subscribed to, then echoes every frame back.
///
/// The `recv` loop is what holds the connection open. Returning from this
/// future drops the socket, which tears the TCP connection down *without* a
/// close handshake — the client then has no close code to report and falls back
/// to `1006 abnormal closure`. An empty `|_socket| async {}` does exactly that.
async fn handle_events(mut socket: WebSocket, filters: EventFilters) {
    let greeting = format!(
        "subscribed to \"{}\" (replay: {})",
        filters.room,
        filters.replay.unwrap_or(0)
    );
    if socket.send(Message::Text(greeting.into())).await.is_err() {
        return;
    }

    while let Some(Ok(message)) = socket.recv().await {
        if let Message::Text(text) = message {
            let echo = format!("[{}] {text}", filters.room);
            if socket.send(Message::Text(echo.into())).await.is_err() {
                return;
            }
        }
    }
}

// lucyd_mqtt only registers documentation metadata; this framework has no real
// MQTT transport of its own, so the handler is invoked directly at startup
// instead of by a broker, to give it a genuine caller.
#[lucyd_mqtt(
    topic = "sensors/temperature",
    tags = "iot",
    description = "Temperature readings"
)]
async fn on_temp() {
    println!("on_temp handler ran (would normally fire on an MQTT message)");
}

/// Publishes a reading every two seconds, so the MQTT panel shows a live feed
/// with no sensor attached.
///
/// It goes onto the same bus a connected client publishes to, which is why the
/// panel sees it simply by subscribing to `sensors/temperature`.
async fn publish_readings(bus: Sender<Publication>) {
    let mut ticker = tokio::time::interval(Duration::from_secs(2));
    for tick in 0u32.. {
        ticker.tick().await;
        let celsius = 20.0 + f64::from(tick % 40) / 10.0;
        // Fails only while nobody is subscribed, which is not an error here.
        let _ = bus.send(Publication::new(
            "sensors/temperature",
            format!("{{\"celsius\":{celsius:.1}}}"),
        ));
    }
}

#[tokio::main]
async fn main() {
    on_temp().await;

    let bus = mqtt_broker::bus();
    tokio::spawn(publish_readings(bus.clone()));

    let app = Router::new()
        .route("/api/ping", post(ping))
        .route("/api/scores", get(scores))
        .route("/ws/events", get(events))
        .merge(mqtt_broker::router(bus))
        .merge(docs_router());

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    println!("listening on http://localhost:3000  (try /docs, /docs/openapi.json)");
    println!(
        "MQTT panel  -> set Broker to ws://localhost:3000{}",
        mqtt_broker::PATH
    );
    axum::serve(listener, app).await.unwrap();
}
