//! Assembles one `syn::File` from the operations extracted by `operations.rs`
//! and the types generated by `rust_type.rs`: a fixed header (module doc
//! comment + `use` statements), every generated `struct`/`enum`, then one
//! `#[lucyd_http]`-annotated stub per non-skipped operation.

use super::operations::ImportOperation;
use super::rust_type::{self, TypeGenerator};
use quote::{format_ident, quote};
use serde_json::Value;

/// Fixed header prepended to every generated file. Parsed through `syn`
/// (rather than hand-built token by token) so a typo here is a
/// `syn::parse_file` panic caught by this crate's own tests, not a silently
/// malformed file handed to a consumer.
///
/// `#![allow(dead_code)]` is a practical necessity, not part of the spec's
/// illustrative shape: a freshly generated stub file's structs/fns are
/// usually not wired into the consumer's router yet, and `rustc`'s
/// `dead_code` lint fires on unreferenced `pub` items in a binary crate.
const HEADER_TEMPLATE: &str = r#"//! Auto-generated by `cargo xtask import-openapi`. Hand-edit freely:
//! re-running the importer preserves any handler body that isn't a bare
//! `todo!()` call untouched. Attributes, signatures, and the struct/enum
//! definitions below are always refreshed from the OpenAPI source.
#![allow(dead_code)]

use lucyd::lucyd_http;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
"#;

/// The Rust types one operation's schemas were generated into, each `None`
/// when the operation declared no such schema.
#[derive(Default)]
struct OperationTypes {
    /// From the folded `in: query` parameters; bound by `query = T`.
    query: Option<syn::Type>,
    request: Option<syn::Type>,
    response: Option<syn::Type>,
}

/// The freshly generated (not yet merged with an existing file) contents.
pub struct GeneratedFile {
    /// Inner (`#![...]`) attributes of the fixed header.
    pub header_attrs: Vec<syn::Attribute>,
    /// `use` items of the fixed header.
    pub header_items: Vec<syn::Item>,
    /// Struct/enum definitions, in first-use (emission) order.
    pub structs: Vec<syn::Item>,
    /// `(operation_id, generated stub fn)`, in spec order, one per
    /// non-skipped operation. `merge.rs` reconciles this against whatever
    /// was already on disk.
    pub operation_fns: Vec<(String, syn::ItemFn)>,
}

/// Generates structs/enums and handler stubs for every non-skipped
/// operation. Skipped operations (`skip_reason.is_some()`) are left out of
/// the generated code entirely — they're surfaced only via `summary.rs`.
pub fn generate(document: &Value, operations: &[ImportOperation]) -> Result<GeneratedFile, String> {
    let mut generator = TypeGenerator::new(document);
    let mut operation_fns = Vec::new();

    for operation in operations {
        if operation.skip_reason.is_some() {
            continue;
        }

        let types = operation_types(&mut generator, operation)?;
        let item_fn = build_operation_fn(operation, &types);
        operation_fns.push((operation.operation_id.clone(), item_fn));
    }

    let header = header_file();
    Ok(GeneratedFile {
        header_attrs: header.attrs,
        header_items: header.items,
        structs: generator.into_items(),
        operation_fns,
    })
}

/// Assembles the final `syn::File` from header + struct + fn items, in that
/// order. Used both for a from-scratch write and, via `merge.rs`, for the
/// reconciled result of merging into an existing file.
pub fn assemble_file(
    header_attrs: Vec<syn::Attribute>,
    header_items: Vec<syn::Item>,
    structs: Vec<syn::Item>,
    fns: Vec<syn::Item>,
) -> syn::File {
    let mut items = header_items;
    items.extend(structs);
    items.extend(fns);
    syn::File {
        shebang: None,
        attrs: header_attrs,
        items,
    }
}

/// Parses [`HEADER_TEMPLATE`] once per generation pass.
fn header_file() -> syn::File {
    syn::parse_file(HEADER_TEMPLATE).expect("HEADER_TEMPLATE must be valid Rust")
}

/// Generates the Rust type behind each of an operation's schemas, naming them
/// `{Op}Params`, `{Op}Request` and `{Op}Response`.
fn operation_types(
    generator: &mut TypeGenerator<'_>,
    operation: &ImportOperation,
) -> Result<OperationTypes, String> {
    let id = rust_type::to_pascal_case(&operation.operation_id);

    Ok(OperationTypes {
        query: named_type(
            generator,
            operation.query_schema.as_ref(),
            &format!("{id}Params"),
        )?,
        request: named_type(
            generator,
            operation.request_schema.as_ref(),
            &format!("{id}Request"),
        )?,
        response: named_type(
            generator,
            operation.response_schema.as_ref(),
            &format!("{id}Response"),
        )?,
    })
}

/// Generates a type for a schema the operation may not have declared.
fn named_type(
    generator: &mut TypeGenerator<'_>,
    schema: Option<&Value>,
    hint: &str,
) -> Result<Option<syn::Type>, String> {
    schema
        .map(|schema| generator.generate_type(schema, hint))
        .transpose()
}

/// Builds one `#[lucyd_http(...)]`-annotated stub function. The signature is
/// deliberately parameter-less — wiring an extractor for the request body is
/// left to the developer implementing the handler; the stub only needs to
/// compile and carry accurate metadata.
fn build_operation_fn(operation: &ImportOperation, types: &OperationTypes) -> syn::ItemFn {
    let doc_attrs = doc_comment_attrs(operation);
    let http_attr = lucyd_http_attr(operation, types);
    let fn_ident = format_ident!("{}", rust_type::to_snake_case(&operation.operation_id));

    let return_type = match &types.response {
        Some(ty) => quote! { -> axum::Json<#ty> },
        None => quote! {},
    };

    let tokens = quote! {
        #(#doc_attrs)*
        #http_attr
        pub async fn #fn_ident() #return_type {
            todo!("Implement handler")
        }
    };
    syn::parse2(tokens).expect("generated fn tokens must parse as an ItemFn")
}

/// Builds the `/// operationId: ...` marker doc comment — load-bearing, see
/// `merge.rs` for why re-imports match on this attribute rather than the fn
/// name — plus an optional path parameter doc line.
///
/// Query parameters used to get a doc line of their own; they are now bound to
/// a generated struct through `query = {Op}Params` instead, so restating them
/// here would only duplicate what the attribute says.
fn doc_comment_attrs(operation: &ImportOperation) -> Vec<proc_macro2::TokenStream> {
    let mut attrs = Vec::new();

    // A leading space matches the shape `syn` produces for a hand-written
    // `/// operationId: ...` (the desugared `#[doc = "..."]` string keeps the
    // space right after the `///`), so the generated file reads the same way
    // either would. `merge.rs::operation_marker` trims before matching, so
    // this is cosmetic, not load-bearing.
    let marker = format!(" operationId: {}", operation.operation_id);
    attrs.push(quote! { #[doc = #marker] });

    if !operation.path_params.is_empty() {
        let line = format!(" Path parameters: {}", operation.path_params.join(", "));
        attrs.push(quote! { #[doc = #line] });
    }

    attrs
}

/// Builds the `#[lucyd_http(method = ..., path = ..., ...)]` attribute,
/// omitting each key the operation doesn't have — matching how the macro
/// already treats `description`/`tags`/`request`/`response` as optional.
fn lucyd_http_attr(
    operation: &ImportOperation,
    types: &OperationTypes,
) -> proc_macro2::TokenStream {
    let method = &operation.method;
    let path = &operation.path;

    let mut args = vec![quote! { method = #method }, quote! { path = #path }];

    if let Some(description) = &operation.description {
        args.push(quote! { description = #description });
    }
    if !operation.tags.is_empty() {
        let tags = operation.tags.join(", ");
        args.push(quote! { tags = #tags });
    }
    if let Some(ty) = &types.query {
        args.push(quote! { query = #ty });
    }
    if let Some(ty) = &types.request {
        args.push(quote! { request = #ty });
    }
    if let Some(ty) = &types.response {
        args.push(quote! { response = #ty });
    }

    quote! { #[lucyd_http(#(#args),*)] }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn operation(id: &str) -> ImportOperation {
        ImportOperation {
            operation_id: id.to_string(),
            method: "GET".to_string(),
            path: "/health".to_string(),
            description: None,
            tags: Vec::new(),
            path_params: Vec::new(),
            query_schema: None,
            request_schema: None,
            response_schema: None,
            skip_reason: None,
        }
    }

    #[test]
    fn header_template_parses_as_valid_rust() {
        let header = header_file();
        assert!(
            !header.attrs.is_empty(),
            "doc comment + allow must produce inner attrs"
        );
        assert_eq!(header.items.len(), 3, "three `use` statements are expected");
    }

    #[test]
    fn skipped_operations_produce_no_fn_or_types() {
        let document = json!({ "openapi": "3.1.0", "paths": {} });
        let mut op = operation("skipped_op");
        op.skip_reason = Some("uses oneOf".to_string());

        let generated = generate(&document, &[op]).expect("generation must succeed");
        assert!(generated.operation_fns.is_empty());
        assert!(generated.structs.is_empty());
    }

    #[test]
    fn stub_body_is_a_bare_todo_call() {
        let document = json!({ "openapi": "3.1.0", "paths": {} });
        let generated =
            generate(&document, &[operation("health")]).expect("generation must succeed");

        assert_eq!(generated.operation_fns.len(), 1);
        let (_, item_fn) = &generated.operation_fns[0];
        let rendered = quote! { #item_fn }.to_string();
        assert!(rendered.contains("todo ! (\"Implement handler\")"));
        assert!(rendered.contains("fn health"));
        assert!(rendered.contains("doc = \" operationId: health\""));
    }

    #[test]
    fn request_and_response_types_appear_in_attribute_and_signature() {
        let document = json!({ "openapi": "3.1.0", "paths": {} });
        let mut op = operation("create_user");
        op.method = "POST".to_string();
        op.path = "/api/users".to_string();
        op.request_schema =
            Some(json!({ "type": "object", "properties": { "name": { "type": "string" } } }));
        op.response_schema =
            Some(json!({ "type": "object", "properties": { "id": { "type": "integer" } } }));

        let generated = generate(&document, &[op]).expect("generation must succeed");
        let (_, item_fn) = &generated.operation_fns[0];
        let rendered = quote! { #item_fn }.to_string();

        assert!(rendered.contains("request = CreateUserRequest"));
        assert!(rendered.contains("response = CreateUserResponse"));
        assert!(rendered.contains("axum :: Json < CreateUserResponse >"));
        assert_eq!(generated.structs.len(), 2);
    }

    #[test]
    fn query_parameters_become_a_params_struct_bound_by_the_attribute() {
        let document = json!({ "openapi": "3.1.0", "paths": {} });
        let mut op = operation("list_scores");
        op.query_schema = Some(json!({
            "type": "object",
            "properties": {
                "board": { "type": "string" },
                "limit": { "type": "integer", "description": "Maximum rows." }
            },
            "required": ["board"]
        }));

        let generated = generate(&document, &[op]).expect("generation must succeed");
        let (_, item_fn) = &generated.operation_fns[0];
        let rendered = quote! { #item_fn }.to_string();

        assert!(
            rendered.contains("query = ListScoresParams"),
            "query parameters must be bound, not downgraded to a doc comment: {rendered}"
        );
        assert!(
            !rendered.contains("Query parameters:"),
            "the doc-comment downgrade this replaces must be gone: {rendered}"
        );

        assert_eq!(generated.structs.len(), 1);
        let struct_tokens = {
            let item = &generated.structs[0];
            quote! { #item }.to_string()
        };
        assert!(struct_tokens.contains("pub struct ListScoresParams"));
        assert!(
            struct_tokens.contains("pub board : String"),
            "a required parameter must be a plain field: {struct_tokens}"
        );
        assert!(
            struct_tokens.contains("pub limit : Option < i64 >"),
            "an optional parameter must be an Option: {struct_tokens}"
        );
        assert!(
            struct_tokens.contains("JsonSchema"),
            "the struct must derive JsonSchema for `query = T` to generate a schema"
        );
    }
}
