//! Builds `docs.md`, the whole documentation as a single file, from the
//! numbered pages in `docs/`.
//!
//! The single file is worth having: it reads offline and pastes somewhere in
//! one piece. Maintaining it by hand is not, which is how it came to sit three
//! pages and several revisions behind `docs/`. The pages are the source, this
//! is the build step.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

/// Directory holding the numbered pages and their index.
const DOCS_DIR: &str = "docs";

/// The generated single-file documentation, at the workspace root.
const OUTPUT: &str = "docs.md";

/// Index page, which supplies the introduction rather than a numbered page.
const INDEX: &str = "README.md";

/// Heading the index's introduction runs up to.
const INDEX_CONTENTS: &str = "\n## Contents";

/// Link back to the index, opening every page and meaningless once merged.
const BACK_LINK: &str = "[← Back to index](README.md)\n\n";

/// Separator between sections, and before a page's navigation footer.
const SECTION_BREAK: &str = "\n---\n";

/// Opening of a Markdown link target.
const LINK_OPEN: &str = "](";

/// Fence delimiter, inside which a leading `#` is a comment, not a heading.
const FENCE: &str = "```";

/// Warns against editing the generated file rather than its source.
const GENERATED_NOTICE: &str = "<!-- Generated by `cargo xtask build-docs` from docs/. \
                                Edit the page in docs/, not this file. -->";

/// One page of the documentation.
struct Page {
    /// File name, which is what sibling pages link to.
    file: String,
    /// The `# ` heading, without its marker.
    title: String,
    body: String,
}

impl Page {
    /// Reads a page and the title it will be listed under.
    fn read(docs: &Path, file: String) -> Result<Self, String> {
        let body = read(&docs.join(&file))?;
        let title = body
            .lines()
            .find_map(|line| line.strip_prefix("# "))
            .ok_or_else(|| format!("`{file}` has no `# ` title"))?
            .to_string();

        Ok(Self { file, title, body })
    }

    /// The anchor this page's title becomes once every page is one document.
    fn anchor(&self) -> String {
        format!("#{}", slug(&self.title))
    }

    /// The title as listed in the table of contents, without its number.
    fn listed_title(&self) -> &str {
        self.title
            .split_once(". ")
            .map_or(self.title.as_str(), |(_, rest)| rest)
    }
}

/// Regenerates `docs.md` from `docs/`.
pub fn build_docs(workspace_root: &Path) -> Result<(), String> {
    let docs = workspace_root.join(DOCS_DIR);
    let pages = read_pages(&docs)?;
    let anchors: BTreeMap<String, String> = pages
        .iter()
        .map(|page| (page.file.clone(), page.anchor()))
        .collect();

    let mut document = header(&read(&docs.join(INDEX))?, &pages)?;
    for page in &pages {
        document.push_str(SECTION_BREAK);
        document.push('\n');
        document.push_str(inline(page, &anchors).trim());
        document.push('\n');
    }

    let output = workspace_root.join(OUTPUT);
    fs::write(&output, document).map_err(|error| format!("cannot write `{OUTPUT}`: {error}"))?;
    println!(
        "==> {} pages written to `{}`",
        pages.len(),
        output.display()
    );
    Ok(())
}

/// Reads every numbered page, in the order their file names sort in.
///
/// The numeric prefix is what orders the documentation, so sorting file names
/// is the ordering rather than an approximation of it.
fn read_pages(docs: &Path) -> Result<Vec<Page>, String> {
    let entries =
        fs::read_dir(docs).map_err(|error| format!("cannot read `{DOCS_DIR}/`: {error}"))?;

    let mut files: Vec<String> = entries
        .filter_map(Result::ok)
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .filter(|name| is_numbered_page(name))
        .collect();
    files.sort();

    if files.is_empty() {
        return Err(format!("no numbered page found in `{DOCS_DIR}/`"));
    }
    files
        .into_iter()
        .map(|file| Page::read(docs, file))
        .collect()
}

/// Whether a file name is a numbered page, e.g. `01-installation.md`.
fn is_numbered_page(name: &str) -> bool {
    let mut characters = name.chars();
    characters.next().is_some_and(|c| c.is_ascii_digit())
        && characters.next().is_some_and(|c| c.is_ascii_digit())
        && characters.next() == Some('-')
        && name.ends_with(".md")
}

/// Builds the title, introduction and table of contents.
fn header(index: &str, pages: &[Page]) -> Result<String, String> {
    let contents: Vec<String> = pages
        .iter()
        .enumerate()
        .map(|(position, page)| {
            format!(
                "{}. [{}]({})",
                position + 1,
                page.listed_title(),
                page.anchor()
            )
        })
        .collect();

    Ok(format!(
        "# Lucyd Documentation\n\n{GENERATED_NOTICE}\n\n{}\n{SECTION_BREAK}\n\
         ## Table of contents\n\n{}\n",
        introduction(index)?,
        contents.join("\n"),
    ))
}

/// The prose between the index's title and its contents table.
fn introduction(index: &str) -> Result<String, String> {
    let after_title = index.split_once('\n').map_or("", |(_, rest)| rest);
    let (introduction, _) = after_title
        .split_once(INDEX_CONTENTS)
        .ok_or_else(|| format!("`{DOCS_DIR}/{INDEX}` has no `## Contents` heading"))?;

    Ok(introduction.trim().to_string())
}

/// Rewrites one page for inclusion in the single file.
fn inline(page: &Page, anchors: &BTreeMap<String, String>) -> String {
    let content = strip_navigation(&page.body);
    rewrite_links(&demote_headings(&content), anchors)
}

/// Drops the links back to the index and on to the next page.
///
/// Both only make sense while the pages are separate files; merged, they point
/// at the reader's current position.
fn strip_navigation(body: &str) -> String {
    let body = body.strip_prefix(BACK_LINK).unwrap_or(body);
    match body.rsplit_once(SECTION_BREAK) {
        Some((content, footer)) if is_navigation(footer) => content.trim_end().to_string(),
        _ => body.trim_end().to_string(),
    }
}

/// Whether a trailing section is a page's navigation footer.
fn is_navigation(section: &str) -> bool {
    let start = section.trim_start();
    start.starts_with("Previous:") || start.starts_with("Next:")
}

/// Pushes every heading down one level, so a page title sits under the
/// document title rather than beside it.
///
/// Fenced blocks are left alone: a leading `#` in a shell example is a comment
/// and demoting it would silently rewrite the command being documented.
fn demote_headings(body: &str) -> String {
    let mut fenced = false;
    let demoted: Vec<String> = body
        .lines()
        .map(|line| {
            if line.starts_with(FENCE) {
                fenced = !fenced;
            }
            match !fenced && line.starts_with('#') {
                true => format!("#{line}"),
                false => line.to_string(),
            }
        })
        .collect();

    demoted.join("\n")
}

/// Turns links to sibling pages into links to the sections they became.
fn rewrite_links(body: &str, anchors: &BTreeMap<String, String>) -> String {
    let mut rewritten = String::with_capacity(body.len());
    let mut rest = body;

    while let Some(position) = rest.find(LINK_OPEN) {
        let (before, target) = rest.split_at(position + LINK_OPEN.len());
        rewritten.push_str(before);

        let Some(end) = target.find(')') else { break };
        rewritten.push_str(&resolve(&target[..end], anchors));
        rest = &target[end..];
    }

    rewritten.push_str(rest);
    rewritten
}

/// The anchor a link target becomes, or the target unchanged when it points
/// somewhere other than a page of this documentation.
///
/// A target that already carries a fragment keeps it: it names a heading,
/// which survives the merge under the same anchor.
fn resolve(target: &str, anchors: &BTreeMap<String, String>) -> String {
    let (file, fragment) = target.split_once('#').unwrap_or((target, ""));
    match (anchors.get(file), fragment) {
        (Some(anchor), "") => anchor.clone(),
        (Some(_), fragment) => format!("#{fragment}"),
        (None, _) => target.to_string(),
    }
}

/// GitHub's heading anchor: lowercased, spaces hyphenated, punctuation dropped.
fn slug(title: &str) -> String {
    title
        .to_lowercase()
        .chars()
        .filter(|c| c.is_alphanumeric() || matches!(c, ' ' | '-' | '_'))
        .map(|c| if c == ' ' { '-' } else { c })
        .collect()
}

/// Reads a file, naming it when it cannot be read.
fn read(path: &Path) -> Result<String, String> {
    fs::read_to_string(path).map_err(|error| format!("cannot read `{}`: {error}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The anchors of a two-page documentation.
    fn anchors() -> BTreeMap<String, String> {
        BTreeMap::from([
            ("02-setup.md".to_string(), "#2-setup".to_string()),
            (
                "11-limitations.md".to_string(),
                "#11-known-limitations-v02".to_string(),
            ),
        ])
    }

    #[test]
    fn a_slug_matches_the_anchor_github_generates() {
        assert_eq!(slug("1. Installation"), "1-installation");
        assert_eq!(
            slug("11. Known limitations (v0.2)"),
            "11-known-limitations-v02"
        );
        assert_eq!(
            slug("6. The OpenAPI export (`/docs/openapi.json`)"),
            "6-the-openapi-export-docsopenapijson"
        );
    }

    #[test]
    fn a_numbered_page_is_recognised_by_its_prefix() {
        assert!(is_numbered_page("01-installation.md"));
        assert!(is_numbered_page("13-openapi-diff.md"));
        assert!(!is_numbered_page("README.md"), "the index is not a page");
        assert!(!is_numbered_page("1-installation.md"), "two digits or none");
        assert!(!is_numbered_page("01-installation.txt"));
    }

    #[test]
    fn navigation_is_dropped_from_both_ends() {
        let page = format!("{BACK_LINK}# 2. Setup\n\nBody.\n\n---\n\nPrevious: [1](01-a.md)\n");

        assert_eq!(strip_navigation(&page), "# 2. Setup\n\nBody.");
    }

    #[test]
    fn a_trailing_rule_that_is_not_navigation_is_kept() {
        let page = "# 2. Setup\n\nBody.\n\n---\n\nA closing note.\n";

        assert_eq!(strip_navigation(page), page.trim_end());
    }

    #[test]
    fn headings_are_demoted_but_shell_comments_are_not() {
        let page = "# 2. Setup\n\n## Details\n\n```bash\n# 1. Run it\ncargo run\n```\n\n## More";

        assert_eq!(
            demote_headings(page),
            "## 2. Setup\n\n### Details\n\n```bash\n# 1. Run it\ncargo run\n```\n\n### More",
            "a `#` inside a fence is a comment, not a heading"
        );
    }

    #[test]
    fn a_link_to_a_sibling_page_becomes_its_anchor() {
        let body = "See [Setup](02-setup.md) and [limits](11-limitations.md).";

        assert_eq!(
            rewrite_links(body, &anchors()),
            "See [Setup](#2-setup) and [limits](#11-known-limitations-v02)."
        );
    }

    #[test]
    fn a_link_carrying_a_fragment_keeps_it() {
        let body = "See [the table](11-limitations.md#status).";

        assert_eq!(rewrite_links(body, &anchors()), "See [the table](#status).");
    }

    #[test]
    fn links_that_are_not_pages_are_left_alone() {
        let body = "[Axum](https://github.com/tokio-rs/axum) and [code](../src/lib.rs).";

        assert_eq!(rewrite_links(body, &anchors()), body);
    }

    #[test]
    fn the_introduction_stops_at_the_contents_table() {
        let index = "# Lucyd Documentation\n\nA library.\n\n## Contents\n\n| # | Page |\n";

        assert_eq!(
            introduction(index).expect("an intro is present"),
            "A library."
        );
    }

    #[test]
    fn an_index_without_a_contents_table_is_an_error() {
        let error = introduction("# Lucyd Documentation\n\nA library.\n")
            .expect_err("the introduction has no end to find");

        assert!(error.contains("## Contents"), "{error}");
    }
}
