//! Manual smoke-test server for the openapi/macro refactor.
//!
//! Run with `cargo run --example demo -p lucyd`, then hit:
//! - http://localhost:3000/docs              (embedded UI)
//! - http://localhost:3000/docs/openapi.json (generated by crates/lucy-core/src/openapi/)
//! - http://localhost:3000/docs/spec.json
//! - POST http://localhost:3000/api/ping

use axum::{
    Router,
    extract::ws::WebSocketUpgrade,
    response::IntoResponse,
    routing::{get, post},
};
use lucyd::{docs_router, lucy_http, lucy_mqtt, lucy_ws};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Deserialize, JsonSchema)]
pub struct Ping {
    pub message: String,
}

#[derive(Serialize, JsonSchema)]
pub struct Pong {
    pub echo: String,
}

#[lucy_http(
    method = "POST",
    path = "/api/ping",
    tags = "system",
    description = "Echo back the message",
    request = Ping,
    response = Pong,
)]
async fn ping(axum::Json(body): axum::Json<Ping>) -> axum::Json<Pong> {
    axum::Json(Pong { echo: body.message })
}

#[lucy_ws(
    path = "/ws/events",
    tags = "realtime",
    description = "Live event stream"
)]
async fn events(ws: WebSocketUpgrade) -> impl IntoResponse {
    ws.on_upgrade(|_socket| async {})
}

// lucy_mqtt only registers documentation metadata; this framework has no real
// MQTT transport of its own, so the handler is invoked directly at startup
// instead of by a broker, to give it a genuine caller.
#[lucy_mqtt(
    topic = "sensors/temperature",
    tags = "iot",
    description = "Temperature readings"
)]
async fn on_temp() {
    println!("on_temp handler ran (would normally fire on an MQTT message)");
}

#[tokio::main]
async fn main() {
    on_temp().await;

    let app = Router::new()
        .route("/api/ping", post(ping))
        .route("/ws/events", get(events))
        .merge(docs_router());

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    println!("listening on http://localhost:3000  (try /docs, /docs/openapi.json)");
    axum::serve(listener, app).await.unwrap();
}
